AWSTemplateFormatVersion: "2010-09-09"
Description: VPC for Fargate

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags:
        - Key: Name
          Value: FargateVPC

  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html#cfn-ec2-vpc-tags

  ExecuteSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: PrivateSubnetForFargate

  DebugSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.20.0/24
      Tags:
        - Key: Name
          Value: PublicSubnetForFargate

  # https://saramune.github.io/objekumo/2019/05/07/20190507/
  # https://docs.aws.amazon.com/ja_jp/vpc/latest/privatelink/vpce-interface.html
  # https://dev.classmethod.jp/articles/privatesubnet_ecs/

  # サービスごとに作成する
  # SQS
  myVPCEndpointForSQS:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ""
        - - com.amazonaws.
          - !Ref "AWS::Region"
          - .sqs
      VpcId: !Ref myVPC
      SubnetIds:
        - !Ref ExecuteSubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref InterfaceSecurityGroup

  # ECR
  myVPCEndpointForECR:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ""
        - - com.amazonaws.
          - !Ref "AWS::Region"
          - .ecr.dkr
      VpcId: !Ref myVPC
      SubnetIds:
        - !Ref ExecuteSubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref InterfaceSecurityGroup

  # ECR
  myVPCEndpointForECRAPI:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ""
        - - com.amazonaws.
          - !Ref "AWS::Region"
          - .ecr.api
      VpcId: !Ref myVPC
      SubnetIds:
        - !Ref ExecuteSubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref InterfaceSecurityGroup

  # S3
  myVPCEndpointForS3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ""
        - - com.amazonaws.
          - !Ref "AWS::Region"
          - .s3
      VpcId: !Ref myVPC
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref RouteTable

  # DynamoDB
  myVPCEndpointForDynamo:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ""
        - - com.amazonaws.
          - !Ref "AWS::Region"
          - .dynamodb
      VpcId: !Ref myVPC
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref RouteTable

  # logs
  myVPCEndpointForLogs:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ""
        - - com.amazonaws.
          - !Ref "AWS::Region"
          - .logs
      VpcId: !Ref myVPC
      SubnetIds:
        - !Ref ExecuteSubnet
      VpcEndpointType: Interface
      PrivateDnsEnabled: True
      SecurityGroupIds:
        - !Ref InterfaceSecurityGroup

  InterfaceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for interfaces
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: 10.0.10.0/24
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 10.0.10.0/24
          FromPort: "443"
          ToPort: "443"
      Tags:
        - Key: Name
          Value: pgname-interface-sg
      VpcId: !Ref myVPC

  # 実行サブネットに紐づけるルートテーブル
  # s3とDynamoDBのエンドポイントに向けてのルートを設定する
  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: pgname-RouteTable
  SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref ExecuteSubnet
